# Default values for rethinkdb_exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dtr.docker-opscare-poc.demo-azure-cs.mirantis.com/admin/rethinkdb-exporter
  tag: 0.1
## Specify an imagePullPolicy (Required)
## It's recommended to change this to 'Always' if the image tag is 'latest'
## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistrKeySecretName  

service:
  containerPort: 9055
  name: http
  type: ClusterIP
  port: 9055
  protocol: TCP

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists 

rethinkdb_exporter:
  dbaddr: '$(POD_NODE_IP):12383' 
  dbtls: true
  ca: /tmp/ucpcerts/ca.pem
  cert: /tmp/ucpcerts/cert.pem
  key: /tmp/ucpcerts/key.pem
  clustername: rethinkdb
  count_rows: true
  stats_table_estimates: true
  log:
    debug: true

env:
- name: POD_NODE_IP
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP 
- name: POD_NODE_NAME
  valueFrom:
    fieldRef:
      fieldPath: spec.nodeName 


serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

certs:
  hostPath: /var/lib/docker/volumes/ucp-node-certs/_data

extraVolumes: []

extraVolumeMounts: []